// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlayT4DkRS42rAbVW9pDPrOJq1QCkptHU',
    appId: '1:332103694730:android:6f92f9f061cabd5b2e7073',
    messagingSenderId: '332103694730',
    projectId: 'ihvan-kardesler-ae5f6',
    storageBucket: 'ihvan-kardesler-ae5f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu6tL8PuWWAknEhzKk0ajQhidx8mjNvxI',
    appId: '1:332103694730:ios:f1d8e4cf85a0bddc2e7073',
    messagingSenderId: '332103694730',
    projectId: 'ihvan-kardesler-ae5f6',
    storageBucket: 'ihvan-kardesler-ae5f6.appspot.com',
    iosClientId: '332103694730-sk61656r5f5g3e5cgs5ssf1br638737u.apps.googleusercontent.com',
    iosBundleId: 'com.hozdemir1968.ihvanKardesler',
  );
}
